
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      instance:
          instance-id: microservicecloud-consumer-dept80         #自定义服务实例名称
          prefer-ip-address: true                                  #是否显示服务IP信息
  instance:
      instance-id: microservicecloud-consumer-dept80         #自定义服务实例名称
      prefer-ip-address: true                                  #是否显示服务IP信息
#点击服务实例名时显示的信息配置
info:
  app.name: zzm-microservicecloud-consumer
  company.name: www.zzm.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: microservicecloud-consumer-dept                  #自定义应用名称